apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    database: contract_analyzer
    jsonData:
      sslmode: disable
      encrypt: disable
    isDefault: true
